import type { Metadata } from "next";
import ThemeSwitcher from "./ThemeSwitcher";
import Providers from "./Providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <section className="h-screen w-screen flex justify-center">
            <main className="h-full w-5/6 flex flex-col">
              <ThemeSwitcher />
              {children}
            </main>
          </section>
        </Providers>
      </body>
    </html>
  );
}
